Vagrant.configure(2) do |config|
  config.vm.define "st2" do |st2|
    st2.vm.network "private_network", type: "dhcp"
    st2.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

    st2.vm.network :forwarded_port, guest: 443, host: 19443, id: 'api'

    st2.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    st2.vm.synced_folder "../", "/vagrant"

    st2.vm.provision "shell", inline: <<-SHELL
      sudo dd if=/dev/zero of=/swapfile bs=1024 count=524288
      sudo chmod 600 /swapfile
      sudo mkswap /swapfile
      sudo swapon /swapfile
      sudo bash /vagrant/vagrant/st2/st2bootstrap-deb.sh
    SHELL

  end
end
